menubar: false
statusbar: false
theme_advanced_path: false
theme_advanced_buttons1: bold, italic, underline, separator, bullist, numlist, separator, outdent, indent, alignleft, aligncenter, alignright
language: 'zh-cn'
