default: &default
  appid: <%= ENV['WECHAT_APP_ID'] %>
  secret: <%= ENV['WECHAT_APP_SECRET'] %>
  token: <%= ENV['WECHAT_APP_TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
